Prueba 2 – Kubernetes Deployment (debugging)
Actividades:
- Detectar y corregir los errores del siguiente manifiesto
- Agregar réplicas
- Mejorar el Deployment aplicando buenas prácticas
Problema:

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
  labels:
    app: python-app  
spec:
  replicas: 3
  selector:
     matchLabels:
     app: python-app
  template:
    metadata:
      labels:
        app: python-app
  spec:
    containers:
    - name: python-app
    image: python:3.11.15-trixie
    ports:
      - containerPort: "8080"
    command: ["python"]
    args: ["app.py"]



Prueba 3: Crear un service de tipo NodePort para exponer el
Deployment anterior.
Objetivo:
Evaluar si el postulante entiende cómo exponer aplicaciones en Kubernetes.
Enunciado:
Crea un Service de tipo NodePort para exponer la aplicación del Deployment anterior.
---

apiVersion: v1
kind: Service
metadata:
  name: python-app
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: python-app
  ports:
    - port: 8080
      # By default and for convenience, the `targetPort` is set to
      # the same value as the `port` field.
      targetPort: 8080
      # Optional field
      # By default and for convenience, the Kubernetes control plane
      # will allocate a port from a range (default: 30000-32767)
      nodePort: 30007    
